project:
  type: book
  output-dir: docs

book:
  title: "Quarto Analysis Book Template"
  author: 
    - "Author 1"
    - "Author 2"
  date: "8/16/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices: 
    - python_env.qmd
    - useful_tools.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



